### ISSUE TITLE
Google Earth Engine integration breaks your tool

### ISSUE THREAD

**Issue by sinanna** [samapriya/Planet-GEE-Pipeline-CLI#3]
I've been trying your guide https://medium.com/planet-stories/planet-people-and-pixels-a-data-pipeline-to-link-planet-api-to-google-earth-engine-1166606445a8

```
Traceback (most recent call last):
  File "ppipe.py", line 12, in <module>
    from taskreport import genreport
  File "/home/XX/ppipe/taskreport.py", line 8, in <module>
    ee.Initialize()
  File "/usr/lib/python3.6/site-packages/ee/__init__.py", line 93, in Initialize
    ApiFunction.initialize()
  File "/usr/lib/python3.6/site-packages/ee/apifunction.py", line 151, in initialize
    signatures = data.getAlgorithms()
  File "/usr/lib/python3.6/site-packages/ee/data.py", line 426, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "/usr/lib/python3.6/site-packages/ee/data.py", line 837, in send_
    response.status)
ee.ee_exception.EEException: Server returned HTTP code: 404
```

I HAVE authorized Google EE with my code 4/AADDvi8WDdQuv3M9hn9lv8WsypAoQKSu5XfYG1i1W_exKoTClCBOJvk

**Comment by samapriya** [comment]
Can you run "earthengine ls" and get your home directory? I am unable to replicate the error
